### ISSUE TITLE
FDS Config Error

### ISSUE THREAD

**Issue by ArthurLee9** [dvershinin/fds#14]
I am receiving an error when trying to run FDS Config on RHEL 8.3.

[root@mail ~]# **fds config**
Traceback (most recent call last):
  File "/usr/bin/fds", line 11, in <module>
    load_entry_point('fds==0.0.19', 'console_scripts', 'fds')()
  File "/usr/lib/python3.6/site-packages/fds/fds.py", line 191, in main
    return action_config()
  File "/usr/lib/python3.6/site-packages/fds/config.py", line 24, in action_config
    open_web_if_webserver_running()
  File "/usr/lib/python3.6/site-packages/fds/config.py", line 8, in open_web_if_webserver_running
    from .utils import is_process_running, query_yes_no
  File "/usr/lib/python3.6/site-packages/fds/utils.py", line 1, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

[root@mail ~]# **fds --version**
fds 0.0.19

**Comment by dvershinin** [comment]
Thank you for your continuous feedback.
Should be fixed in v0.0.20
