### ISSUE TITLE
fds block Asia crashes

### ISSUE THREAD

**Issue by ajweber** [dvershinin/fds#36]
Trying to do as title says on Centos 7.

Can send the entire output, but the last lines are as follows:
`Starting new HTTP connection (1): www.ipdeny.com
Downloaded /var/lib/fds/ge.zone: : 16KB [00:00, 30311.14KB/s]
Done!
Skipped update in Cloudflare as it was not set up. Run fds config?
Traceback (most recent call last):
  File "/usr/bin/fds", line 9, in <module>
    load_entry_point('fds==0.0.37', 'console_scripts', 'fds')()
  File "/usr/lib/python2.7/site-packages/fds/fds.py", line 208, in main
    return action_block(args.value, args.ipset_name, reload=args.reload)
  File "/usr/lib/python2.7/site-packages/fds/fds.py", line 62, in action_block
    block_region(ip_or_country_name)
  File "/usr/lib/python2.7/site-packages/fds/fds.py", line 42, in block_region
    action_block(country.name, reload=False)
  File "/usr/lib/python2.7/site-packages/fds/fds.py", line 47, in action_block
    fw = FirewallWrapper()
  File "/usr/lib/python2.7/site-packages/fds/FirewallWrapper.py", line 67, in __init__
    self.fw = FirewallClient()
  File "<string>", line 2, in __init__
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 53, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 2509, in __init__
    path_keyword='path')
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 160, in add_signal_receiver
    self.add_match_string(str(match))
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 398, in add_match_string
    BUS_DAEMON_IFACE, 'AddMatch', 's', (rule,))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.LimitsExceeded: Connection ":1.28" is not allowed to add more match rules (increase limits in configuration file if required)`

**Comment by dvershinin** [comment]
@ajweber please check, should be fixed in fds-0.0.38
